# Generated by Django 5.2.12 on 2026-03-27 12:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_eyebrow_en', models.CharField(blank=True, max_length=255)),
                ('hero_eyebrow_fr', models.CharField(blank=True, max_length=255)),
                ('hero_title_en', models.CharField(blank=True, max_length=255)),
                ('hero_title_fr', models.CharField(blank=True, max_length=255)),
                ('hero_body_en', wagtail.fields.RichTextField(blank=True)),
                ('hero_body_fr', wagtail.fields.RichTextField(blank=True)),
                ('intro_heading_en', models.CharField(blank=True, max_length=255)),
                ('intro_heading_fr', models.CharField(blank=True, max_length=255)),
                ('intro_body_en', wagtail.fields.RichTextField(blank=True)),
                ('intro_body_fr', wagtail.fields.RichTextField(blank=True)),
                ('featured_tiles_en', wagtail.fields.StreamField([('tile', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('cta_label', 0), ('cta_href', 0)]], {})}, default=list)),
                ('featured_tiles_fr', wagtail.fields.StreamField([('tile', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('cta_label', 0), ('cta_href', 0)]], {})}, default=list)),
                ('sections_en', wagtail.fields.StreamField([('rich_section', 2), ('feature_stack', 7), ('gallery', 10), ('faq', 13), ('cta_section', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 3), ('body', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 6)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 9), ('caption', 0)]], {}), 11: ('wagtail.blocks.StructBlock', [[('question', 3), ('answer', 1)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 12)]], {}), 14: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 4), ('button_label', 3), ('button_url', 3)]], {})}, default=list)),
                ('sections_fr', wagtail.fields.StreamField([('rich_section', 2), ('feature_stack', 7), ('gallery', 10), ('faq', 13), ('cta_section', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 3), ('body', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 6)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 9), ('caption', 0)]], {}), 11: ('wagtail.blocks.StructBlock', [[('question', 3), ('answer', 1)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 12)]], {}), 14: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 4), ('button_label', 3), ('button_url', 3)]], {})}, default=list)),
                ('seo_title_en', models.CharField(blank=True, max_length=255)),
                ('seo_title_fr', models.CharField(blank=True, max_length=255)),
                ('seo_description_en', models.TextField(blank=True)),
                ('seo_description_fr', models.TextField(blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NarrativePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('route_key', models.CharField(choices=[('about', 'About'), ('studios', 'Studios'), ('film-projects', 'Film projects'), ('cinema', 'Cinema'), ('contact', 'Contact')], max_length=64)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_body', wagtail.fields.RichTextField(blank=True)),
                ('sections', wagtail.fields.StreamField([('rich_section', 2), ('feature_stack', 7), ('gallery', 10), ('faq', 13), ('cta_section', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 3), ('body', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 6)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 9), ('caption', 0)]], {}), 11: ('wagtail.blocks.StructBlock', [[('question', 3), ('answer', 1)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 12)]], {}), 14: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 4), ('button_label', 3), ('button_url', 3)]], {})}, default=list)),
                ('primary_cta_label', models.CharField(blank=True, max_length=120)),
                ('primary_cta_url', models.CharField(blank=True, max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narrative_pages', to='wagtailcore.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'route_key', 'language_code'), name='unique_narrative_page_per_site_route_locale')],
            },
            bases=('wagtailcore.page',),
        ),
    ]
