# Generated by Django 5.2.12 on 2026-03-27 16:06

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_title_override', models.CharField(blank=True, max_length=255)),
                ('seo_title_override_fr', models.CharField(blank=True, max_length=255)),
                ('seo_description_override', models.TextField(blank=True)),
                ('seo_description_override_fr', models.TextField(blank=True)),
                ('title_display', models.CharField(blank=True, max_length=255)),
                ('title_display_fr', models.CharField(blank=True, max_length=255)),
                ('intro_text', wagtail.fields.RichTextField(blank=True)),
                ('intro_text_fr', wagtail.fields.RichTextField(blank=True)),
                ('form_embed', models.TextField(blank=True)),
                ('form_embed_fr', models.TextField(blank=True)),
                ('map_embed', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_title_override', models.CharField(blank=True, max_length=255)),
                ('seo_title_override_fr', models.CharField(blank=True, max_length=255)),
                ('seo_description_override', models.TextField(blank=True)),
                ('seo_description_override_fr', models.TextField(blank=True)),
                ('title_display', models.CharField(blank=True, max_length=255)),
                ('title_display_fr', models.CharField(blank=True, max_length=255)),
                ('intro_text', wagtail.fields.RichTextField(blank=True)),
                ('intro_text_fr', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='SpacesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_title_override', models.CharField(blank=True, max_length=255)),
                ('seo_title_override_fr', models.CharField(blank=True, max_length=255)),
                ('seo_description_override', models.TextField(blank=True)),
                ('seo_description_override_fr', models.TextField(blank=True)),
                ('title_display', models.CharField(blank=True, max_length=255)),
                ('title_display_fr', models.CharField(blank=True, max_length=255)),
                ('intro_text', wagtail.fields.RichTextField(blank=True)),
                ('intro_text_fr', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_tiles_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_tiles_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_body_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_body_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_eyebrow_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_eyebrow_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_body_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_body_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_heading_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_heading_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sections_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sections_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='seo_description_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='seo_title_fr',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('feature_grid', 6), ('project_highlights', 9), ('gallery', 12), ('collaborators', 15), ('awards', 18), ('cta_band', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('description', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 1), ('items', 5)]], {}), 7: ('wagtail.snippets.blocks.SnippetChooserBlock', ('pages.Project',), {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 1), ('projects', 8)]], {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 11), ('caption', 0)]], {}), 13: ('wagtail.blocks.StructBlock', [[('name', 2), ('role', 0), ('note', 3)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 14)]], {}), 16: ('wagtail.blocks.StructBlock', [[('title', 2), ('detail', 0)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 17)]], {}), 19: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 1), ('label', 2), ('href', 2)]], {})}, default=list),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_fr',
            field=wagtail.fields.StreamField([('feature_grid', 6), ('project_highlights', 9), ('gallery', 12), ('collaborators', 15), ('awards', 18), ('cta_band', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('description', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 1), ('items', 5)]], {}), 7: ('wagtail.snippets.blocks.SnippetChooserBlock', ('pages.Project',), {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 1), ('projects', 8)]], {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 11), ('caption', 0)]], {}), 13: ('wagtail.blocks.StructBlock', [[('name', 2), ('role', 0), ('note', 3)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 14)]], {}), 16: ('wagtail.blocks.StructBlock', [[('title', 2), ('detail', 0)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 17)]], {}), 19: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 1), ('label', 2), ('href', 2)]], {})}, default=list),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_fr',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_cta_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_cta_label_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_cta_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_cta_label_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_description_override',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_description_override_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title_override_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_title_override', models.CharField(blank=True, max_length=255)),
                ('seo_title_override_fr', models.CharField(blank=True, max_length=255)),
                ('seo_description_override', models.TextField(blank=True)),
                ('seo_description_override_fr', models.TextField(blank=True)),
                ('title_display', models.CharField(blank=True, max_length=255)),
                ('title_display_fr', models.CharField(blank=True, max_length=255)),
                ('intro_title', models.CharField(blank=True, max_length=255)),
                ('intro_title_fr', models.CharField(blank=True, max_length=255)),
                ('intro_text', wagtail.fields.RichTextField(blank=True)),
                ('intro_text_fr', wagtail.fields.RichTextField(blank=True)),
                ('services', wagtail.fields.StreamField([('rich_text', 2), ('feature_grid', 8), ('gallery', 11), ('cta_band', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 3), ('items', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 10), ('caption', 0)]], {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 3), ('label', 4), ('href', 4)]], {})}, default=list)),
                ('services_fr', wagtail.fields.StreamField([('rich_text', 2), ('feature_grid', 8), ('gallery', 11), ('cta_band', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 3), ('items', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 10), ('caption', 0)]], {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 3), ('label', 4), ('href', 4)]], {})}, default=list)),
                ('studios_equipment', wagtail.fields.StreamField([('rich_text', 2), ('feature_grid', 8), ('gallery', 11), ('cta_band', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 3), ('items', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 10), ('caption', 0)]], {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 3), ('label', 4), ('href', 4)]], {})}, default=list)),
                ('studios_equipment_fr', wagtail.fields.StreamField([('rich_text', 2), ('feature_grid', 8), ('gallery', 11), ('cta_band', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 3), ('items', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 10), ('caption', 0)]], {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 3), ('label', 4), ('href', 4)]], {})}, default=list)),
                ('intro_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('has_public_profile', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('role_fr', models.CharField(blank=True, max_length=255)),
                ('short_bio', models.TextField(blank=True)),
                ('short_bio_fr', models.TextField(blank=True)),
                ('full_bio', wagtail.fields.RichTextField(blank=True)),
                ('full_bio_fr', wagtail.fields.RichTextField(blank=True)),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='pages.aboutpage')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.person')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('person', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.person')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_fr', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('has_public_page', models.BooleanField(default=False)),
                ('project_type', models.CharField(blank=True, max_length=255)),
                ('project_type_fr', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=32)),
                ('roles', models.TextField(blank=True)),
                ('roles_fr', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('short_description_fr', models.TextField(blank=True)),
                ('full_description', wagtail.fields.StreamField([('rich_text', 2), ('feature_grid', 8), ('gallery', 11), ('cta_band', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 3), ('items', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 10), ('caption', 0)]], {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 3), ('label', 4), ('href', 4)]], {})}, default=list)),
                ('full_description_fr', wagtail.fields.StreamField([('rich_text', 2), ('feature_grid', 8), ('gallery', 11), ('cta_band', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 3), ('items', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 10), ('caption', 0)]], {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 3), ('label', 4), ('href', 4)]], {})}, default=list)),
                ('video_embed', models.TextField(blank=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PersonRelatedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('person', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_projects', to='pages.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.project')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_collaborations', to='pages.person')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='pages.project')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('caption_fr', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pages.project')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectsPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('title_fr', models.CharField(blank=True, max_length=255)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('intro_fr', wagtail.fields.RichTextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.projectspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectsPageSectionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.project')),
                ('section', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='pages.projectspagesection')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_fr', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('short_description_fr', models.TextField(blank=True)),
                ('size', models.CharField(blank=True, max_length=255)),
                ('capacity', models.CharField(blank=True, max_length=255)),
                ('equipment', wagtail.fields.RichTextField(blank=True)),
                ('equipment_fr', wagtail.fields.RichTextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=255)),
                ('cta_label_fr', models.CharField(blank=True, max_length=255)),
                ('cta_link', models.CharField(blank=True, max_length=255)),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('caption_fr', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('space', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pages.space')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpaceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('title_fr', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('notes_fr', models.TextField(blank=True)),
                ('space', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='pages.space')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpacesPageSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='pages.spacespage')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.space')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_title_override', models.CharField(blank=True, max_length=255)),
                ('seo_title_override_fr', models.CharField(blank=True, max_length=255)),
                ('seo_description_override', models.TextField(blank=True)),
                ('seo_description_override_fr', models.TextField(blank=True)),
                ('title_display', models.CharField(blank=True, max_length=255)),
                ('title_display_fr', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('subtitle_fr', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.StreamField([('rich_text', 2), ('feature_grid', 8), ('gallery', 11), ('cta_band', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 3), ('items', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 10), ('caption', 0)]], {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 3), ('label', 4), ('href', 4)]], {})}, default=list)),
                ('body_fr', wagtail.fields.StreamField([('rich_text', 2), ('feature_grid', 8), ('gallery', 11), ('cta_band', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 3), ('items', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 10), ('caption', 0)]], {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 3), ('label', 4), ('href', 4)]], {})}, default=list)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.DeleteModel(
            name='NarrativePage',
        ),
    ]
