# Generated by Django 5.2.12 on 2026-03-27 18:12

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactpage_projectspage_spacespage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='space',
            name='cta_label_fr',
        ),
        migrations.RemoveField(
            model_name='space',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='space',
            name='size',
        ),
        migrations.RemoveField(
            model_name='spaceoffering',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='spaceoffering',
            name='notes_fr',
        ),
        migrations.RemoveField(
            model_name='spaceoffering',
            name='price',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='catalog_section',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='catalog_section_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='directors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='directors_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='languages_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='listing_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='listing_summary_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='production_countries',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='production_countries_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='synopsis',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='synopsis_fr',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='space',
            name='area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='space',
            name='booking_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='space',
            name='booking_label_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='space',
            name='booking_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='spaceoffering',
            name='area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='spaceoffering',
            name='capacity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='spaceoffering',
            name='daily_rate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='spaceoffering',
            name='extra_services',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='spaceoffering',
            name='extra_services_fr',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='spaceoffering',
            name='hourly_rate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='spaceoffering',
            name='included_features',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='spaceoffering',
            name='included_features_fr',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('highlight_strip', 5), ('feature_grid', 9), ('project_highlights', 12), ('gallery', 15), ('collaborations', 19), ('awards', 22), ('cta_band', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('body', 2), ('link_label', 0), ('link_url', 0)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 1), ('description', 2)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 6), ('items', 8)]], {}), 10: ('wagtail.snippets.blocks.SnippetChooserBlock', ('pages.Project',), {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 6), ('projects', 11)]], {}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 14), ('caption', 0)]], {}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('name', 1), ('image', 16), ('link_url', 0), ('note', 2)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 6), ('items', 18)]], {}), 20: ('wagtail.blocks.StructBlock', [[('title', 1), ('detail', 0)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 6), ('label', 1), ('href', 1)]], {})}, default=list),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_fr',
            field=wagtail.fields.StreamField([('highlight_strip', 5), ('feature_grid', 9), ('project_highlights', 12), ('gallery', 15), ('collaborations', 19), ('awards', 22), ('cta_band', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('body', 2), ('link_label', 0), ('link_url', 0)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 1), ('description', 2)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 6), ('items', 8)]], {}), 10: ('wagtail.snippets.blocks.SnippetChooserBlock', ('pages.Project',), {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 6), ('projects', 11)]], {}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('images', 14), ('caption', 0)]], {}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('name', 1), ('image', 16), ('link_url', 0), ('note', 2)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 6), ('items', 18)]], {}), 20: ('wagtail.blocks.StructBlock', [[('title', 1), ('detail', 0)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('heading', 0), ('items', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 6), ('label', 1), ('href', 1)]], {})}, default=list),
        ),
        migrations.CreateModel(
            name='ProjectCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role', models.CharField(max_length=255)),
                ('role_fr', models.CharField(blank=True, max_length=255)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('value_fr', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credited_projects', to='pages.person')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='pages.project')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=255)),
                ('label_fr', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='pages.project')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
