# Generated by Django 5.2.12 on 2026-03-27 12:10

import django.db.models.deletion
import siteconfig.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_slug', models.SlugField(default='lighthouse-labs', max_length=80)),
                ('default_locale', models.CharField(default='en', max_length=2)),
                ('supported_locales', models.JSONField(blank=True, default=siteconfig.models.default_locales)),
                ('color_primary', models.CharField(default='#1d2a44', max_length=20)),
                ('color_secondary', models.CharField(default='#6a1f2b', max_length=20)),
                ('color_accent', models.CharField(default='#d9b26f', max_length=20)),
                ('background_color', models.CharField(default='#f4efe7', max_length=20)),
                ('font_family_token', models.CharField(default='Iowan Old Style, Georgia, serif', max_length=255)),
                ('logo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteChromeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_nav', wagtail.fields.StreamField([('item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('label_en', 0), ('label_fr', 0), ('href', 0), ('open_in_new_tab', 1)]], {})}, default=list)),
                ('footer_groups', wagtail.fields.StreamField([('group', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('label_en', 0), ('label_fr', 0), ('href', 0), ('open_in_new_tab', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.StructBlock', [[('title_en', 0), ('title_fr', 0), ('links', 3)]], {})}, default=list)),
                ('social_links', wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1)]], {})}, default=list)),
                ('contact_heading_en', models.CharField(blank=True, max_length=255)),
                ('contact_heading_fr', models.CharField(blank=True, max_length=255)),
                ('contact_body_en', wagtail.fields.RichTextField(blank=True)),
                ('contact_body_fr', wagtail.fields.RichTextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('announcement_label_en', models.CharField(blank=True, max_length=255)),
                ('announcement_label_fr', models.CharField(blank=True, max_length=255)),
                ('announcement_body_en', models.CharField(blank=True, max_length=255)),
                ('announcement_body_fr', models.CharField(blank=True, max_length=255)),
                ('announcement_link_label_en', models.CharField(blank=True, max_length=255)),
                ('announcement_link_label_fr', models.CharField(blank=True, max_length=255)),
                ('announcement_link_url', models.CharField(blank=True, max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
