# Generated by Django 5.2.12 on 2026-03-27 16:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsettings',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='brandsettings',
            name='color_accent',
        ),
        migrations.RemoveField(
            model_name='brandsettings',
            name='color_primary',
        ),
        migrations.RemoveField(
            model_name='brandsettings',
            name='color_secondary',
        ),
        migrations.RemoveField(
            model_name='brandsettings',
            name='font_family_token',
        ),
        migrations.RemoveField(
            model_name='brandsettings',
            name='logo_image',
        ),
        migrations.RemoveField(
            model_name='brandsettings',
            name='site_slug',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='announcement_body_en',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='announcement_body_fr',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='announcement_label_en',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='announcement_label_fr',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='announcement_link_label_en',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='announcement_link_url',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='contact_body_en',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='contact_body_fr',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='contact_heading_en',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='contact_heading_fr',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='footer_groups',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='primary_nav',
        ),
        migrations.RemoveField(
            model_name='sitechromesettings',
            name='social_links',
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='primary_color',
            field=models.CharField(default='#1d2a44', max_length=20),
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='secondary_color',
            field=models.CharField(default='#b85c38', max_length=20),
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='site_name',
            field=models.CharField(default='Lighthouse Labs', max_length=255),
        ),
        migrations.AddField(
            model_name='sitechromesettings',
            name='announcement_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitechromesettings',
            name='announcement_link_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitechromesettings',
            name='announcement_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitechromesettings',
            name='announcement_text_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitechromesettings',
            name='footer_columns',
            field=wagtail.fields.StreamField([('column', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('label_fr', 1), ('href', 0), ('open_in_new_tab', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('title_fr', 1), ('links', 4)]], {})}, default=list),
        ),
        migrations.AddField(
            model_name='sitechromesettings',
            name='nav_items',
            field=wagtail.fields.StreamField([('item', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('label_fr', 1), ('href', 0), ('open_in_new_tab', 2)]], {})}, default=list),
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('google_maps_link', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('vimeo', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
