# Generated by Django 5.2.12 on 2026-03-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_remove_brandsettings_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsettings',
            name='default_locale',
            field=models.CharField(default='fr', max_length=2),
        ),
    ]
